//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IaService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveUserRequest", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class SaveUserRequest : object
    {
        
        private IaService.IAUser[] IAUsersField;
        
        private IaService.ImportType ImportTypeField;
        
        private IaService.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.IAUser[] IAUsers
        {
            get
            {
                return this.IAUsersField;
            }
            set
            {
                this.IAUsersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.ImportType ImportType
        {
            get
            {
                return this.ImportTypeField;
            }
            set
            {
                this.ImportTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class User : object
    {
        
        private string NameField;
        
        private string PassWordField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PassWord
        {
            get
            {
                return this.PassWordField;
            }
            set
            {
                this.PassWordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IAUser", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class IAUser : object
    {
        
        private IaService.Authorization[] AuthorizationsField;
        
        private string EmailField;
        
        private string EmploymentUnitExternalIdField;
        
        private string ExternalIdField;
        
        private string FirstNameField;
        
        private IaService.UserStatus StatusField;
        
        private string SurNameField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.Authorization[] Authorizations
        {
            get
            {
                return this.AuthorizationsField;
            }
            set
            {
                this.AuthorizationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EmploymentUnitExternalId
        {
            get
            {
                return this.EmploymentUnitExternalIdField;
            }
            set
            {
                this.EmploymentUnitExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ExternalId
        {
            get
            {
                return this.ExternalIdField;
            }
            set
            {
                this.ExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.UserStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SurName
        {
            get
            {
                return this.SurNameField;
            }
            set
            {
                this.SurNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportType", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public enum ImportType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Total = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Change = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authorization", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class Authorization : object
    {
        
        private IaService.UserRoleType RoleField;
        
        private IaService.AuthorizationUnits UnitsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.UserRoleType Role
        {
            get
            {
                return this.RoleField;
            }
            set
            {
                this.RoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.AuthorizationUnits Units
        {
            get
            {
                return this.UnitsField;
            }
            set
            {
                this.UnitsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserStatus", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public enum UserStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorizationUnits", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class AuthorizationUnits : object
    {
        
        private string[] ExternalIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string[] ExternalId
        {
            get
            {
                return this.ExternalIdField;
            }
            set
            {
                this.ExternalIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRoleType", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public enum UserRoleType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Manager = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OHSRepresentative = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OccurrenceManager = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvestigatorAndActionOwner = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IaService.SaveUserFlatResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IaService.SaveEmployeeResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IaService.SaveOrganizationalUnitsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IaService.GetOccurrenceCountByOrganizationalUnitResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IaService.GetLatestOccurrenceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IaService.SaveActionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IaService.GetActionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IaService.GetOccurrenceExcelDataResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IaService.GetFlaggedOccurrencesResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IaService.SaveUserResponse))]
    public partial class ResponseBase : object
    {
        
        private string ErrorTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ErrorText
        {
            get
            {
                return this.ErrorTextField;
            }
            set
            {
                this.ErrorTextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveUserFlatResponse", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class SaveUserFlatResponse : IaService.ResponseBase
    {
        
        private IaService.ImportResult[] ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.ImportResult[] Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveEmployeeResponse", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class SaveEmployeeResponse : IaService.ResponseBase
    {
        
        private IaService.ImportResult[] ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.ImportResult[] Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveOrganizationalUnitsResponse", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class SaveOrganizationalUnitsResponse : IaService.ResponseBase
    {
        
        private IaService.ImportResult[] ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.ImportResult[] Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOccurrenceCountByOrganizationalUnitResponse", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class GetOccurrenceCountByOrganizationalUnitResponse : IaService.ResponseBase
    {
        
        private IaService.OccurrenceCount[] OccurrenceCountField;
        
        private string OrganizationalUnitNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.OccurrenceCount[] OccurrenceCount
        {
            get
            {
                return this.OccurrenceCountField;
            }
            set
            {
                this.OccurrenceCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OrganizationalUnitName
        {
            get
            {
                return this.OrganizationalUnitNameField;
            }
            set
            {
                this.OrganizationalUnitNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLatestOccurrenceResponse", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class GetLatestOccurrenceResponse : IaService.ResponseBase
    {
        
        private string CourseOfEventField;
        
        private string EmploymentUnitNameField;
        
        private long OccurrenceIdField;
        
        private System.DateTime OccurrencePeriodField;
        
        private IaService.OccurrenceType OccurrenceTypeField;
        
        private string OrganizationalUnitNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CourseOfEvent
        {
            get
            {
                return this.CourseOfEventField;
            }
            set
            {
                this.CourseOfEventField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmploymentUnitName
        {
            get
            {
                return this.EmploymentUnitNameField;
            }
            set
            {
                this.EmploymentUnitNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long OccurrenceId
        {
            get
            {
                return this.OccurrenceIdField;
            }
            set
            {
                this.OccurrenceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime OccurrencePeriod
        {
            get
            {
                return this.OccurrencePeriodField;
            }
            set
            {
                this.OccurrencePeriodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.OccurrenceType OccurrenceType
        {
            get
            {
                return this.OccurrenceTypeField;
            }
            set
            {
                this.OccurrenceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OrganizationalUnitName
        {
            get
            {
                return this.OrganizationalUnitNameField;
            }
            set
            {
                this.OrganizationalUnitNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveActionResponse", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class SaveActionResponse : IaService.ResponseBase
    {
        
        private IaService.ImportResult[] ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.ImportResult[] Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetActionResponse", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class GetActionResponse : IaService.ResponseBase
    {
        
        private IaService.ActionExport[] ActionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.ActionExport[] Actions
        {
            get
            {
                return this.ActionsField;
            }
            set
            {
                this.ActionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOccurrenceExcelDataResponse", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class GetOccurrenceExcelDataResponse : IaService.ResponseBase
    {
        
        private byte[] FileContentField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] FileContent
        {
            get
            {
                return this.FileContentField;
            }
            set
            {
                this.FileContentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFlaggedOccurrencesResponse", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class GetFlaggedOccurrencesResponse : IaService.ResponseBase
    {
        
        private IaService.FlaggedOccurrence[] OccurrencesField;
        
        private string OrganizationalUnitNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.FlaggedOccurrence[] Occurrences
        {
            get
            {
                return this.OccurrencesField;
            }
            set
            {
                this.OccurrencesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OrganizationalUnitName
        {
            get
            {
                return this.OrganizationalUnitNameField;
            }
            set
            {
                this.OrganizationalUnitNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveUserResponse", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class SaveUserResponse : IaService.ResponseBase
    {
        
        private IaService.ImportResult[] ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.ImportResult[] Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportResult", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class ImportResult : object
    {
        
        private string ExternalIdField;
        
        private string MessageField;
        
        private IaService.ImportResultStatus StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ExternalId
        {
            get
            {
                return this.ExternalIdField;
            }
            set
            {
                this.ExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.ImportResultStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportResultStatus", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public enum ImportResultStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OccurrenceCount", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class OccurrenceCount : object
    {
        
        private long CountField;
        
        private IaService.OccurrenceType OccurrenceTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Count
        {
            get
            {
                return this.CountField;
            }
            set
            {
                this.CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.OccurrenceType OccurrenceType
        {
            get
            {
                return this.OccurrenceTypeField;
            }
            set
            {
                this.OccurrenceTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OccurrenceType", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public enum OccurrenceType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Accident = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CommutingAccident = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WorkRelatedIllness = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NearMiss = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Environment = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Facility = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RiskObservation = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Safety = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Quality = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ImprovementProposal = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OtherDivergence = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SafetyObservation = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pupil = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Preschooler = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CareRecipient = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Patient = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZeroAccident = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LTI = 76,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionExport", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class ActionExport : object
    {
        
        private long ActionIdField;
        
        private int ActionNoField;
        
        private string ActionOwnerExternalIdField;
        
        private string ActionOwnerNameField;
        
        private string ActionOwnerOtherField;
        
        private IaService.ActionStepType ActionStepField;
        
        private string ActionTextField;
        
        private string ActionTitleField;
        
        private string EstimatedCompletionDateField;
        
        private string OccurrenceNoField;
        
        private string OrganizationField;
        
        private string OrganizationalUnitExternalIdField;
        
        private string OrganizationalUnitNameField;
        
        private string ResponsibleExternalIdField;
        
        private string ResponsibleNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long ActionId
        {
            get
            {
                return this.ActionIdField;
            }
            set
            {
                this.ActionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ActionNo
        {
            get
            {
                return this.ActionNoField;
            }
            set
            {
                this.ActionNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ActionOwnerExternalId
        {
            get
            {
                return this.ActionOwnerExternalIdField;
            }
            set
            {
                this.ActionOwnerExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ActionOwnerName
        {
            get
            {
                return this.ActionOwnerNameField;
            }
            set
            {
                this.ActionOwnerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ActionOwnerOther
        {
            get
            {
                return this.ActionOwnerOtherField;
            }
            set
            {
                this.ActionOwnerOtherField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.ActionStepType ActionStep
        {
            get
            {
                return this.ActionStepField;
            }
            set
            {
                this.ActionStepField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ActionText
        {
            get
            {
                return this.ActionTextField;
            }
            set
            {
                this.ActionTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ActionTitle
        {
            get
            {
                return this.ActionTitleField;
            }
            set
            {
                this.ActionTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EstimatedCompletionDate
        {
            get
            {
                return this.EstimatedCompletionDateField;
            }
            set
            {
                this.EstimatedCompletionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OccurrenceNo
        {
            get
            {
                return this.OccurrenceNoField;
            }
            set
            {
                this.OccurrenceNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Organization
        {
            get
            {
                return this.OrganizationField;
            }
            set
            {
                this.OrganizationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OrganizationalUnitExternalId
        {
            get
            {
                return this.OrganizationalUnitExternalIdField;
            }
            set
            {
                this.OrganizationalUnitExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OrganizationalUnitName
        {
            get
            {
                return this.OrganizationalUnitNameField;
            }
            set
            {
                this.OrganizationalUnitNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ResponsibleExternalId
        {
            get
            {
                return this.ResponsibleExternalIdField;
            }
            set
            {
                this.ResponsibleExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ResponsibleName
        {
            get
            {
                return this.ResponsibleNameField;
            }
            set
            {
                this.ResponsibleNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionStepType", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public enum ActionStepType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Elimination = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exchange = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TechnologicalProtectionActions = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MarkingWarningSystemsProceduresEtc = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PersonalProtectiveEquipment = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlaggedOccurrence", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class FlaggedOccurrence : object
    {
        
        private string FlagTextField;
        
        private string FlagTitleField;
        
        private System.DateTime OccurrenceDateField;
        
        private string OccurrenceDescriptionField;
        
        private long OccurrenceIdField;
        
        private int OccurrenceNumberField;
        
        private string OccurrenceTitleField;
        
        private string OrganizationalUnitNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FlagText
        {
            get
            {
                return this.FlagTextField;
            }
            set
            {
                this.FlagTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FlagTitle
        {
            get
            {
                return this.FlagTitleField;
            }
            set
            {
                this.FlagTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime OccurrenceDate
        {
            get
            {
                return this.OccurrenceDateField;
            }
            set
            {
                this.OccurrenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OccurrenceDescription
        {
            get
            {
                return this.OccurrenceDescriptionField;
            }
            set
            {
                this.OccurrenceDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long OccurrenceId
        {
            get
            {
                return this.OccurrenceIdField;
            }
            set
            {
                this.OccurrenceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OccurrenceNumber
        {
            get
            {
                return this.OccurrenceNumberField;
            }
            set
            {
                this.OccurrenceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OccurrenceTitle
        {
            get
            {
                return this.OccurrenceTitleField;
            }
            set
            {
                this.OccurrenceTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OrganizationalUnitName
        {
            get
            {
                return this.OrganizationalUnitNameField;
            }
            set
            {
                this.OrganizationalUnitNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveUserFlatRequest", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class SaveUserFlatRequest : object
    {
        
        private IaService.IAUserFlat[] IAUsersField;
        
        private IaService.ImportType ImportTypeField;
        
        private IaService.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.IAUserFlat[] IAUsers
        {
            get
            {
                return this.IAUsersField;
            }
            set
            {
                this.IAUsersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.ImportType ImportType
        {
            get
            {
                return this.ImportTypeField;
            }
            set
            {
                this.ImportTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IAUserFlat", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class IAUserFlat : object
    {
        
        private string EmailField;
        
        private string EmploymentUnitExternalIdField;
        
        private string ExternalIdField;
        
        private string FirstNameField;
        
        private string OccurrenceUnitExternalIdField;
        
        private IaService.UserRoleType RoleField;
        
        private IaService.UserStatus StatusField;
        
        private string SurNameField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EmploymentUnitExternalId
        {
            get
            {
                return this.EmploymentUnitExternalIdField;
            }
            set
            {
                this.EmploymentUnitExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ExternalId
        {
            get
            {
                return this.ExternalIdField;
            }
            set
            {
                this.ExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OccurrenceUnitExternalId
        {
            get
            {
                return this.OccurrenceUnitExternalIdField;
            }
            set
            {
                this.OccurrenceUnitExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.UserRoleType Role
        {
            get
            {
                return this.RoleField;
            }
            set
            {
                this.RoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.UserStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SurName
        {
            get
            {
                return this.SurNameField;
            }
            set
            {
                this.SurNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveEmployeeRequest", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class SaveEmployeeRequest : object
    {
        
        private IaService.Employee[] EmployeesField;
        
        private IaService.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.Employee[] Employees
        {
            get
            {
                return this.EmployeesField;
            }
            set
            {
                this.EmployeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class Employee : object
    {
        
        private string AddressField;
        
        private string CellPhoneField;
        
        private string CityField;
        
        private string EmailField;
        
        private string EmployedSinceField;
        
        private string EmploymentUnitExternalIdField;
        
        private string ExternalIdField;
        
        private string NameField;
        
        private string PersonalIdNoField;
        
        private string PhoneField;
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CellPhone
        {
            get
            {
                return this.CellPhoneField;
            }
            set
            {
                this.CellPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EmployedSince
        {
            get
            {
                return this.EmployedSinceField;
            }
            set
            {
                this.EmployedSinceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EmploymentUnitExternalId
        {
            get
            {
                return this.EmploymentUnitExternalIdField;
            }
            set
            {
                this.EmploymentUnitExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ExternalId
        {
            get
            {
                return this.ExternalIdField;
            }
            set
            {
                this.ExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PersonalIdNo
        {
            get
            {
                return this.PersonalIdNoField;
            }
            set
            {
                this.PersonalIdNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveOrganizationalUnitsWithLoginRequest", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class SaveOrganizationalUnitsWithLoginRequest : object
    {
        
        private IaService.ImportType ImportTypeField;
        
        private IaService.OrganizationalUnit[] OrganizationalUnitsField;
        
        private IaService.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.ImportType ImportType
        {
            get
            {
                return this.ImportTypeField;
            }
            set
            {
                this.ImportTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.OrganizationalUnit[] OrganizationalUnits
        {
            get
            {
                return this.OrganizationalUnitsField;
            }
            set
            {
                this.OrganizationalUnitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationalUnit", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class OrganizationalUnit : object
    {
        
        private string CfarNrField;
        
        private string ExternalIdField;
        
        private string ExternalIdParentField;
        
        private string NameField;
        
        private IaService.OrganizationalUnitStatus StatusField;
        
        private IaService.OrganizationalUnitType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CfarNr
        {
            get
            {
                return this.CfarNrField;
            }
            set
            {
                this.CfarNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ExternalId
        {
            get
            {
                return this.ExternalIdField;
            }
            set
            {
                this.ExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ExternalIdParent
        {
            get
            {
                return this.ExternalIdParentField;
            }
            set
            {
                this.ExternalIdParentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.OrganizationalUnitStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.OrganizationalUnitType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationalUnitStatus", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public enum OrganizationalUnitStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationalUnitType", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public enum OrganizationalUnitType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Both = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Occurrence = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Employment = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOccurrenceCountByOrganizationalUnitRequest", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class GetOccurrenceCountByOrganizationalUnitRequest : object
    {
        
        private bool IncludeContractorsField;
        
        private bool IncludeLightField;
        
        private bool IncludeSubUnitsField;
        
        private string OrganizationalUnitNameField;
        
        private IaService.OrganizationalUnitType OrganizationalUnitTypeField;
        
        private string PeriodEndField;
        
        private string PeriodStartField;
        
        private IaService.DatePeriodType PeriodTypeField;
        
        private IaService.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IncludeContractors
        {
            get
            {
                return this.IncludeContractorsField;
            }
            set
            {
                this.IncludeContractorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IncludeLight
        {
            get
            {
                return this.IncludeLightField;
            }
            set
            {
                this.IncludeLightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IncludeSubUnits
        {
            get
            {
                return this.IncludeSubUnitsField;
            }
            set
            {
                this.IncludeSubUnitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OrganizationalUnitName
        {
            get
            {
                return this.OrganizationalUnitNameField;
            }
            set
            {
                this.OrganizationalUnitNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IaService.OrganizationalUnitType OrganizationalUnitType
        {
            get
            {
                return this.OrganizationalUnitTypeField;
            }
            set
            {
                this.OrganizationalUnitTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PeriodEnd
        {
            get
            {
                return this.PeriodEndField;
            }
            set
            {
                this.PeriodEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PeriodStart
        {
            get
            {
                return this.PeriodStartField;
            }
            set
            {
                this.PeriodStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.DatePeriodType PeriodType
        {
            get
            {
                return this.PeriodTypeField;
            }
            set
            {
                this.PeriodTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatePeriodType", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public enum DatePeriodType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Registration = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Occurrence = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Change = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLatestOccurrenceRequest", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class GetLatestOccurrenceRequest : object
    {
        
        private bool IncludeContractorsField;
        
        private bool IncludeLightField;
        
        private bool IncludeSubUnitsField;
        
        private IaService.OccurrenceSearchType OccurrenceTypeField;
        
        private string OrganizationalUnitNameField;
        
        private IaService.OrganizationalUnitType OrganizationalUnitTypeField;
        
        private IaService.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IncludeContractors
        {
            get
            {
                return this.IncludeContractorsField;
            }
            set
            {
                this.IncludeContractorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IncludeLight
        {
            get
            {
                return this.IncludeLightField;
            }
            set
            {
                this.IncludeLightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IncludeSubUnits
        {
            get
            {
                return this.IncludeSubUnitsField;
            }
            set
            {
                this.IncludeSubUnitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.OccurrenceSearchType OccurrenceType
        {
            get
            {
                return this.OccurrenceTypeField;
            }
            set
            {
                this.OccurrenceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OrganizationalUnitName
        {
            get
            {
                return this.OrganizationalUnitNameField;
            }
            set
            {
                this.OrganizationalUnitNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IaService.OrganizationalUnitType OrganizationalUnitType
        {
            get
            {
                return this.OrganizationalUnitTypeField;
            }
            set
            {
                this.OrganizationalUnitTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OccurrenceSearchType", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public enum OccurrenceSearchType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Accident = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CommutingAccident = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WorkRelatedIllness = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NearMiss = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Environment = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Facility = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RiskObservation = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Safety = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Quality = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ImprovementProposal = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OtherDivergence = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SafetyObservation = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pupil = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Preschooler = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CareRecipient = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Patient = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllAccidents = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZeroAccident = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LTI = 76,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveActionRequest", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class SaveActionRequest : object
    {
        
        private IaService.Action[] ActionsField;
        
        private IaService.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.Action[] Actions
        {
            get
            {
                return this.ActionsField;
            }
            set
            {
                this.ActionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Action", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class Action : object
    {
        
        private long ActionIdField;
        
        private string ActionOwnerExternalIdField;
        
        private string ActionOwnerOtherField;
        
        private IaService.ActionStepType ActionStepField;
        
        private string ActionTextField;
        
        private bool CompletedField;
        
        private string EstimatedCompletionDateField;
        
        private string WorkOrderNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long ActionId
        {
            get
            {
                return this.ActionIdField;
            }
            set
            {
                this.ActionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ActionOwnerExternalId
        {
            get
            {
                return this.ActionOwnerExternalIdField;
            }
            set
            {
                this.ActionOwnerExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ActionOwnerOther
        {
            get
            {
                return this.ActionOwnerOtherField;
            }
            set
            {
                this.ActionOwnerOtherField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.ActionStepType ActionStep
        {
            get
            {
                return this.ActionStepField;
            }
            set
            {
                this.ActionStepField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ActionText
        {
            get
            {
                return this.ActionTextField;
            }
            set
            {
                this.ActionTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Completed
        {
            get
            {
                return this.CompletedField;
            }
            set
            {
                this.CompletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EstimatedCompletionDate
        {
            get
            {
                return this.EstimatedCompletionDateField;
            }
            set
            {
                this.EstimatedCompletionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string WorkOrderNumber
        {
            get
            {
                return this.WorkOrderNumberField;
            }
            set
            {
                this.WorkOrderNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetActionRequest", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class GetActionRequest : object
    {
        
        private string OccurrencePeriodEndField;
        
        private string OccurrencePeriodStartField;
        
        private IaService.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OccurrencePeriodEnd
        {
            get
            {
                return this.OccurrencePeriodEndField;
            }
            set
            {
                this.OccurrencePeriodEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OccurrencePeriodStart
        {
            get
            {
                return this.OccurrencePeriodStartField;
            }
            set
            {
                this.OccurrencePeriodStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IaService.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOccurrenceExcelDataRequest", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class GetOccurrenceExcelDataRequest : object
    {
        
        private int ExportDataVersionField;
        
        private bool HideEmptyColumnsField;
        
        private string PeriodEndField;
        
        private string PeriodStartField;
        
        private IaService.DatePeriodType PeriodTypeField;
        
        private bool ShowStaticColumnsField;
        
        private IaService.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExportDataVersion
        {
            get
            {
                return this.ExportDataVersionField;
            }
            set
            {
                this.ExportDataVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HideEmptyColumns
        {
            get
            {
                return this.HideEmptyColumnsField;
            }
            set
            {
                this.HideEmptyColumnsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PeriodEnd
        {
            get
            {
                return this.PeriodEndField;
            }
            set
            {
                this.PeriodEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PeriodStart
        {
            get
            {
                return this.PeriodStartField;
            }
            set
            {
                this.PeriodStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IaService.DatePeriodType PeriodType
        {
            get
            {
                return this.PeriodTypeField;
            }
            set
            {
                this.PeriodTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowStaticColumns
        {
            get
            {
                return this.ShowStaticColumnsField;
            }
            set
            {
                this.ShowStaticColumnsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IaService.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFlaggedOccurrencesRequest", Namespace="http://schemas.datacontract.org/2004/07/IAIntegrationWCF2")]
    public partial class GetFlaggedOccurrencesRequest : object
    {
        
        private bool IncludeSubUnitsField;
        
        private string OccurrencePeriodEndField;
        
        private string OccurrencePeriodStartField;
        
        private string OrganizationalUnitNameField;
        
        private IaService.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IncludeSubUnits
        {
            get
            {
                return this.IncludeSubUnitsField;
            }
            set
            {
                this.IncludeSubUnitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OccurrencePeriodEnd
        {
            get
            {
                return this.OccurrencePeriodEndField;
            }
            set
            {
                this.OccurrencePeriodEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OccurrencePeriodStart
        {
            get
            {
                return this.OccurrencePeriodStartField;
            }
            set
            {
                this.OccurrencePeriodStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OrganizationalUnitName
        {
            get
            {
                return this.OrganizationalUnitNameField;
            }
            set
            {
                this.OrganizationalUnitNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IaService.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://prevention.afa.se/Prevention/2014/01", ConfigurationName="IaService.IIaIntegrationSi")]
    public interface IIaIntegrationSi
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/SaveUsers", ReplyAction="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/SaveUsersResponse")]
        System.Threading.Tasks.Task<IaService.SaveUserResponse> SaveUsersAsync(IaService.SaveUserRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/SaveUsersFlat", ReplyAction="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/SaveUsersFlatRespons" +
            "e")]
        System.Threading.Tasks.Task<IaService.SaveUserFlatResponse> SaveUsersFlatAsync(IaService.SaveUserFlatRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/SaveEmployees", ReplyAction="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/SaveEmployeesRespons" +
            "e")]
        System.Threading.Tasks.Task<IaService.SaveEmployeeResponse> SaveEmployeesAsync(IaService.SaveEmployeeRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/SaveEmployeesQueue", ReplyAction="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/SaveEmployeesQueueRe" +
            "sponse")]
        System.Threading.Tasks.Task<IaService.SaveEmployeeResponse> SaveEmployeesQueueAsync(IaService.SaveEmployeeRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/SaveOrganizationalUn" +
            "itsWithLogin", ReplyAction="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/SaveOrganizationalUn" +
            "itsWithLoginResponse")]
        System.Threading.Tasks.Task<IaService.SaveOrganizationalUnitsResponse> SaveOrganizationalUnitsWithLoginAsync(IaService.SaveOrganizationalUnitsWithLoginRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/GetOccurrenceCountBy" +
            "OrganizationalUnit", ReplyAction="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/GetOccurrenceCountBy" +
            "OrganizationalUnitResponse")]
        System.Threading.Tasks.Task<IaService.GetOccurrenceCountByOrganizationalUnitResponse> GetOccurrenceCountByOrganizationalUnitAsync(IaService.GetOccurrenceCountByOrganizationalUnitRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/GetLatestOccurrence", ReplyAction="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/GetLatestOccurrenceR" +
            "esponse")]
        System.Threading.Tasks.Task<IaService.GetLatestOccurrenceResponse> GetLatestOccurrenceAsync(IaService.GetLatestOccurrenceRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/IsAlive", ReplyAction="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/IsAliveResponse")]
        System.Threading.Tasks.Task<bool> IsAliveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/IsAliveWithDependenc" +
            "ies", ReplyAction="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/IsAliveWithDependenc" +
            "iesResponse")]
        System.Threading.Tasks.Task<bool> IsAliveWithDependenciesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/SaveAction", ReplyAction="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/SaveActionResponse")]
        System.Threading.Tasks.Task<IaService.SaveActionResponse> SaveActionAsync(IaService.SaveActionRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/GetAction", ReplyAction="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/GetActionResponse")]
        System.Threading.Tasks.Task<IaService.GetActionResponse> GetActionAsync(IaService.GetActionRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/GetOccurrenceExcelDa" +
            "ta", ReplyAction="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/GetOccurrenceExcelDa" +
            "taResponse")]
        System.Threading.Tasks.Task<IaService.GetOccurrenceExcelDataResponse> GetOccurrenceExcelDataAsync(IaService.GetOccurrenceExcelDataRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/GetFlaggedOccurrence" +
            "s", ReplyAction="http://prevention.afa.se/Prevention/2014/01/IIaIntegrationSi/GetFlaggedOccurrence" +
            "sResponse")]
        System.Threading.Tasks.Task<IaService.GetFlaggedOccurrencesResponse> GetFlaggedOccurrencesAsync(IaService.GetFlaggedOccurrencesRequest req);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IIaIntegrationSiChannel : IaService.IIaIntegrationSi, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class IaIntegrationSiClient : System.ServiceModel.ClientBase<IaService.IIaIntegrationSi>, IaService.IIaIntegrationSi
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IaIntegrationSiClient() : 
                base(IaIntegrationSiClient.GetDefaultBinding(), IaIntegrationSiClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IIaIntegrationSi.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IaIntegrationSiClient(EndpointConfiguration endpointConfiguration) : 
                base(IaIntegrationSiClient.GetBindingForEndpoint(endpointConfiguration), IaIntegrationSiClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IaIntegrationSiClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IaIntegrationSiClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IaIntegrationSiClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IaIntegrationSiClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IaIntegrationSiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<IaService.SaveUserResponse> SaveUsersAsync(IaService.SaveUserRequest req)
        {
            return base.Channel.SaveUsersAsync(req);
        }
        
        public System.Threading.Tasks.Task<IaService.SaveUserFlatResponse> SaveUsersFlatAsync(IaService.SaveUserFlatRequest req)
        {
            return base.Channel.SaveUsersFlatAsync(req);
        }
        
        public System.Threading.Tasks.Task<IaService.SaveEmployeeResponse> SaveEmployeesAsync(IaService.SaveEmployeeRequest req)
        {
            return base.Channel.SaveEmployeesAsync(req);
        }
        
        public System.Threading.Tasks.Task<IaService.SaveEmployeeResponse> SaveEmployeesQueueAsync(IaService.SaveEmployeeRequest req)
        {
            return base.Channel.SaveEmployeesQueueAsync(req);
        }
        
        public System.Threading.Tasks.Task<IaService.SaveOrganizationalUnitsResponse> SaveOrganizationalUnitsWithLoginAsync(IaService.SaveOrganizationalUnitsWithLoginRequest req)
        {
            return base.Channel.SaveOrganizationalUnitsWithLoginAsync(req);
        }
        
        public System.Threading.Tasks.Task<IaService.GetOccurrenceCountByOrganizationalUnitResponse> GetOccurrenceCountByOrganizationalUnitAsync(IaService.GetOccurrenceCountByOrganizationalUnitRequest req)
        {
            return base.Channel.GetOccurrenceCountByOrganizationalUnitAsync(req);
        }
        
        public System.Threading.Tasks.Task<IaService.GetLatestOccurrenceResponse> GetLatestOccurrenceAsync(IaService.GetLatestOccurrenceRequest req)
        {
            return base.Channel.GetLatestOccurrenceAsync(req);
        }
        
        public System.Threading.Tasks.Task<bool> IsAliveAsync()
        {
            return base.Channel.IsAliveAsync();
        }
        
        public System.Threading.Tasks.Task<bool> IsAliveWithDependenciesAsync()
        {
            return base.Channel.IsAliveWithDependenciesAsync();
        }
        
        public System.Threading.Tasks.Task<IaService.SaveActionResponse> SaveActionAsync(IaService.SaveActionRequest req)
        {
            return base.Channel.SaveActionAsync(req);
        }
        
        public System.Threading.Tasks.Task<IaService.GetActionResponse> GetActionAsync(IaService.GetActionRequest req)
        {
            return base.Channel.GetActionAsync(req);
        }
        
        public System.Threading.Tasks.Task<IaService.GetOccurrenceExcelDataResponse> GetOccurrenceExcelDataAsync(IaService.GetOccurrenceExcelDataRequest req)
        {
            return base.Channel.GetOccurrenceExcelDataAsync(req);
        }
        
        public System.Threading.Tasks.Task<IaService.GetFlaggedOccurrencesResponse> GetFlaggedOccurrencesAsync(IaService.GetFlaggedOccurrencesRequest req)
        {
            return base.Channel.GetFlaggedOccurrencesAsync(req);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IIaIntegrationSi))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IIaIntegrationSi))
            {
                return new System.ServiceModel.EndpointAddress("https://ia.afaforsakring.se/IAIntegrationWCF2/IaIntegrationSi.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IaIntegrationSiClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IIaIntegrationSi);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return IaIntegrationSiClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IIaIntegrationSi);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IIaIntegrationSi,
        }
    }
}
